---

- name: install prerequisite packages
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: add repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    update_cache: yes

- name: install docker
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes